### Implements Heisenberg/Landau-Lifshitz-Gilbert dynamics for rotor spins on
### lattices generated by lattice_methods.py.
### Jonathan B. Curtis

import numpy as np
import lattice_methods as lm
import pickle

PI = np.pi
TWOPI = 2.*PI 

class dynamics:
	"""
	Finite-temperature Landau-Lifshitz-Gilbert(+Brown) dynamics.

	The lattice object is expected to expose:
		- N: number of sites
		- sites: iterable over site indices
		- partners[i]: interacting neighbors of site i
		- J_matrix[j, i]: exchange coupling between j and i

	Units are dimensionless by default: hbar = k_B = 1.  With these
	conventions Brown's fluctuation-dissipation relation gives a thermal field
	with per-component standard deviation sqrt(2 * gilbert * T / dt).
	"""

	def __init__(
		self,
		latt,
		nsteps,
		temp,
		anisotropy=0.,
		gilbert = 1., 
		dt=1.0e-3,
		distances=None,
	):

		### Lattice object encodes geometry and (possibly frustrated) couplings
		self.latt = latt

		### Convenient tuples for storing data shapes in vector and angular representations 
		self.spins_shape = (3,self.latt.N)
		self.angle_shape = (2,self.latt.N)

		### Uniaxial anisotropy (homogeneous) -- negative means easy axis
		self.anisotropy = float(anisotropy)

		### Temperature
		self.temp = float(temp)

		### Optional distances for computing local field traces
		self.distances = None if distances is None else np.atleast_1d(np.asarray(distances,dtype=float))
		self._local_field_kernel = None
		if self.distances is not None:
			self._local_field_kernel = self.latt.magnetic_field_mask_tensor(self.distances)

		### Number of stored time points. The initial state is sample 0.
		self.nsteps = int(nsteps)
		if self.nsteps <= 0:
			raise ValueError("nsteps must be positive.")

		### Dimensionless Gilbert damping alpha 
		self.gilbert = float(gilbert)

		self.dt = float(dt)
		if self.dt <= 0.0:
			raise ValueError("dt must be positive.")

		self.seed = None
		self.rng = np.random.default_rng()

		### We store the state in terms of an angular representation 
		self.angles = self._random_angles()

	### Initialize seed for dynamics
	def set_seed(self, seed):
		self.seed = seed
		self.rng = np.random.default_rng(self.seed)
		### We also reset the initial state using the newly set generator 
		self.angles = self._random_angles() 

	### Initialize dynamics from an existing rng stream
	def set_rng(self, rng, seed=None):
		self.seed = seed
		self.rng = rng

	### Initialize angles to a random state
	def _random_angles(self, seed=None):
		rng = self.rng if seed is None else np.random.default_rng(seed)
		angles = np.zeros(self.angle_shape)
		angles[1,:] = rng.uniform(0.,TWOPI,self.latt.N)
		angles[0,:] = np.arccos(rng.uniform(-1.,1.,self.latt.N))
		return angles 

	### Set angles to a preset state (useful for annealing from a previous run)
	def set_angles(self, angles):
		angles = np.asarray(angles, dtype=float)
		if angles.shape != self.angle_shape:
			raise ValueError(f"angles must have shape (2, {self.latt.N}).")
		self.angles = self._wrap_angles(angles)

	### Set the internal angle state from a normalized vector spin configuration
	def set_spins(self, spins):
		self.angles = self.vector_to_angles(spins)

	### Vector spins are computed on demand and are not stored as dynamical state
	@property
	def spins(self):
		return self.angle_to_vector(self.angles)

	@staticmethod
	def _wrap_angles(angles):
		### Canonicalize theta to [0, pi] and phi to [0, 2pi).
		angles = np.asarray(angles, dtype=float).copy()
		theta = np.mod(angles[0, :], TWOPI)
		phi = angles[1, :]

		reflected = theta > PI
		theta[reflected] = TWOPI - theta[reflected]
		phi[reflected] += PI

		angles[0, :] = theta
		angles[1, :] = np.mod(phi, TWOPI)
		return angles

	### Converts an array of shape (2, ...) containing (theta, phi) to vectors.
	@staticmethod
	def angle_to_vector(angles):
		angles = np.asarray(angles, dtype=float)
		if angles.shape[0] != 2:
			raise ValueError("angles must have leading dimension 2: (theta, phi).")

		theta = angles[0, ...]
		phi = angles[1, ...]
		Sz = np.cos(theta)
		Sx = np.sin(theta) * np.cos(phi)
		Sy = np.sin(theta) * np.sin(phi)

		return np.stack([Sx, Sy, Sz])

	### Converts an array of shape (3, ...) of vectors to rotor angles.
	@staticmethod
	def vector_to_angles(vector, atol=1.0e-8):
		vector = np.asarray(vector, dtype=float)
		if vector.shape[0] != 3:
			raise ValueError("vector must have leading dimension 3: (Sx, Sy, Sz).")

		norm = np.linalg.norm(vector, axis=0)
		if not np.allclose(norm, 1.0, atol=atol):
			raise ValueError("Spin vectors are not normalized.")

		Sx = vector[0, ...]
		Sy = vector[1, ...]
		Sz = np.clip(vector[2, ...], -1.0, 1.0)
		theta = np.arccos(Sz)
		phi = np.arctan2(Sy, Sx)

		return np.stack([theta, phi])

	def _exchange_field(self, spins):
		### B_i = -dH/dS_i for H_ex = -1/2 sum_ij J_ij S_i . S_j.
		### Use the lattice object's partner lists instead of rebuilding graph data here
		field = np.zeros_like(spins)
		for i in self.latt.sites:
			for j in self.latt.partners[i]:
				field[:, i] += self.latt.J_matrix[j, i] * spins[:, j]
		return field

	def _anisotropy_field(self, spins):
		### H_aniso = K sum_i Sz_i^2, so negative K is easy-axis.
		field = np.zeros_like(spins)
		field[2, :] = -2.0 * self.anisotropy * spins[2, :]
		return field

	def _effective_field(self, spins):
		### The deterministic field is the exchange contribution plus anisotropy
		return self._exchange_field(spins) + self._anisotropy_field(spins)

	def _thermal_field(self):
		### Brown field amplitude is fixed by the fluctuation-dissipation relation
		std = np.sqrt(2.0 * self.gilbert * self.temp / self.dt)
		return self.rng.normal(scale=std, size=(3, self.latt.N))

	def _llg_rhs(self, spins, field):
		### Landau-Lifshitz-Gilbert equation in dimensionless units
		alpha = self.gilbert
		prefactor = -1./ (1.0 + alpha**2)
		precession = np.cross(spins.T, field.T).T
		damping = np.cross(spins.T, precession.T).T

		return prefactor * (precession + alpha * damping)

	def _single_time_step(self, angles):
		"""
		Advance one stochastic LLG step using projected Euler dynamics.
		"""
		### Convert angles to vectors for the actual dynamical update
		angles = self._wrap_angles(angles)
		spins = self.angle_to_vector(angles)
		noise = self._thermal_field()

		### Euler step in vector spin space
		### TODO: This is the natural place to upgrade to a fixed-step midpoint method if more stability is needed
		field = self._effective_field(spins) + noise
		spin_rhs = self._llg_rhs(spins, field)
		next_spins = spins + self.dt * spin_rhs

		### Project back to the unit sphere before converting to angle storage
		next_spins /= np.linalg.norm(next_spins, axis=0)[None, :]
		return self.vector_to_angles(next_spins)

	### Advance the internal angular state by one fixed-temperature timestep
	def step(self):
	
		self.angles = self._single_time_step(self.angles)
		return self.angles

	def energy(self, spins=None):
		### Energy is evaluated in the vector representation for compactness
		if spins is None:
			spins = self.spins

		### TODO: Check exchange sign convention before using this dynamics quantitatively
		### Glauber positive J currently corresponds to antiferromagnetic coupling
		### Reuse the sparse exchange field so energy has the same scaling as dynamics
		exchange = -0.5 * np.sum(spins * self._exchange_field(spins))
		anisotropy = self.anisotropy * np.sum(spins[2, :]**2)
		return exchange + anisotropy

	def magnetization(self, spins=None):
		### Uniform magnetization vector averaged over all lattice sites
		if spins is None:
			spins = self.spins
		return np.mean(spins, axis=1)

	def neel_order(self, spins=None):
		### Staggered magnetization for the current square-lattice convention
		if spins is None:
			spins = self.spins

		mask = self.latt.neel_mask()
		return np.mean(spins * mask[None, :], axis=1)

	def stripe_order(self, spins=None):
		### Stripe magnetization vectors along X and Y stripe masks
		if spins is None:
			spins = self.spins

		stripe_x_mask, stripe_y_mask = self.latt.stripe_masks()
		stripe_x = np.mean(spins * stripe_x_mask[None, :], axis=1)
		stripe_y = np.mean(spins * stripe_y_mask[None, :], axis=1)
		return np.stack([stripe_x, stripe_y])

	def local_field(self, spins=None):
		### Local field from the lattice-provided dipolar tensor
		if self._local_field_kernel is None:
			return None
		if spins is None:
			spins = self.spins

		return np.einsum("abnd,bn->ad", self._local_field_kernel, spins)

	def run(self, initial_spins=None, initial_angles=None, snapshot_steps=None):
		### Run fixed-temperature dynamics and sample every timestep from t=0
		if initial_spins is not None and initial_angles is not None:
			raise ValueError("Pass initial_spins or initial_angles, not both.")
		if initial_spins is not None:
			self.set_spins(initial_spins)
		elif initial_angles is not None:
			self.set_angles(initial_angles)

		energies = np.zeros(self.nsteps)
		magnetizations = np.zeros((self.nsteps, 3))
		neels = np.zeros((self.nsteps, 3))
		stripes = np.zeros((2,self.nsteps,3))
		local_field = None
		if self.distances is not None:
			local_field = np.zeros((3, len(self.distances), self.nsteps))
		snapshots = None
		snapshot_indices = {}
		if snapshot_steps is not None:
			snapshot_steps = np.atleast_1d(np.asarray(snapshot_steps,dtype=int))
			if len(snapshot_steps) > 0:
				if np.any(snapshot_steps < 0) or np.any(snapshot_steps >= self.nsteps):
					raise ValueError("snapshot_steps must be between 0 and nsteps - 1.")
				if len(np.unique(snapshot_steps)) != len(snapshot_steps):
					raise ValueError("snapshot_steps cannot contain duplicate step indices.")
				snapshots = np.zeros((len(snapshot_steps),*self.spins_shape))
			snapshot_indices = {int(step): idx for idx, step in enumerate(snapshot_steps)}
		frozen_moment = np.zeros(self.spins_shape)

		for i in range(self.nsteps):
			if i > 0:
				self.step()

			spins = self.spins
			energies[i] = self.energy(spins)
			magnetizations[i, :] = self.magnetization(spins)
			neels[i, :] = self.neel_order(spins)
			stripes[:,i,:] = self.stripe_order(spins)
			if local_field is not None:
				local_field[...,i] = self.local_field(spins)
			if i in snapshot_indices:
				snapshots[snapshot_indices[i],...] = spins
			frozen_moment += spins

		frozen_moment /= float(self.nsteps)
		q_ea = np.mean(np.sum(frozen_moment**2, axis=0))

		return energies, magnetizations, neels, stripes, q_ea, local_field, snapshots


def anneal_dynamics_lattice(
	lattice,
	nsteps,
	temperature_schedule,
	dt=1.0e-3,
	gilbert=0.1,
	anisotropy=0.0,
	distances=None,
	initial_seed=None,
	dynamics_seed=None,
	snapshot_steps=None,
):
	"""
	Low-memory convenience wrapper mirroring glauber_dynamics.anneal_dynamics_lattice.

	Annealing is external to the dynamics class: each temperature gets a
	fixed-temperature dynamics instance initialized from the previous final state.
	"""
	temperature_schedule = np.atleast_1d(np.asarray(temperature_schedule, dtype=float))
	nT = len(temperature_schedule)
	nsteps = int(nsteps)
	distances = None if distances is None else np.atleast_1d(np.asarray(distances,dtype=float))
	snapshot_steps = None if snapshot_steps is None else np.atleast_1d(np.asarray(snapshot_steps,dtype=int))
	if snapshot_steps is not None:
		if len(snapshot_steps) > 0:
			if np.any(snapshot_steps < 0) or np.any(snapshot_steps >= nsteps):
				raise ValueError("snapshot_steps must be between 0 and nsteps - 1.")
			if len(np.unique(snapshot_steps)) != len(snapshot_steps):
				raise ValueError("snapshot_steps cannot contain duplicate step indices.")

	energies = np.zeros((nT, nsteps))
	magnetization = np.zeros((nT, nsteps, 3))
	neel = np.zeros((nT, nsteps, 3))
	stripes = np.zeros((2,nT,nsteps,3))
	local_field = None
	if distances is not None:
		local_field = np.zeros((nT, 3, len(distances), nsteps))
	snapshots = None
	if snapshot_steps is not None and len(snapshot_steps) > 0:
		snapshots = np.zeros((nT,len(snapshot_steps),3,lattice.N))
	qea = np.zeros(nT)

	previous_angles = None 

	### Use one reproducible RNG stream for all temperatures if requested
	dynamics_rng = np.random.default_rng(dynamics_seed) if dynamics_seed is not None else None

	for n, T in enumerate(temperature_schedule):
		sim = dynamics(
			lattice,
			nsteps=nsteps,
			temp=T,
			anisotropy=anisotropy,
			gilbert=gilbert,
			dt=dt,
			distances=distances,
		)


		if n == 0 and initial_seed is not None:
			sim.set_angles(sim._random_angles(seed=initial_seed))

		if previous_angles is not None:
			sim.set_angles(previous_angles)
			
		if dynamics_rng is not None:
			sim.set_rng(dynamics_rng, seed=dynamics_seed)


		run_energies, run_mags, run_neel, run_stripes, run_qea, run_local_field, run_snapshots = sim.run(
			snapshot_steps=snapshot_steps,
		)

		previous_angles = sim.angles

		energies[n, :] = run_energies
		magnetization[n, :, :] = run_mags
		neel[n, :, :] = run_neel
		stripes[:,n,:,:] = run_stripes
		if local_field is not None:
			local_field[n, ...] = run_local_field
		if snapshots is not None:
			snapshots[n, ...] = run_snapshots
		qea[n] = run_qea

	return energies, magnetization, neel, stripes, qea, local_field, snapshots


### Saves a compact output and is low memory usage during operation
### Mirrors the batch-job wrapper structure in glauber_dynamics.run_sims
def run_sims(
	save_filename,
	L,
	Jnnn,
	p,
	J_seed,
	nsteps,
	temps,
	distances,
	replica,
	anisotropy,
	gilbert=0.1,
	dt=1.0e-3,
	initial_seed=None,
	dynamics_seed=None,
	snapshot_sweeps=None,
):
	L = int(L)
	J_seed = int(J_seed)
	nsteps = int(nsteps)
	replica = int(replica)

	### Build the lattice internally so batch jobs only pass simple parameters
	latt = lm.lattice(L)
	latt.set_seed(J_seed)
	latt.set_nn_J(1.,1.)
	latt.set_nnn_J(Jnnn,p)

	results = anneal_dynamics_lattice(
		latt,
		nsteps,
		temps,
		dt=dt,
		gilbert=gilbert,
		anisotropy=anisotropy,
		distances=distances,
		initial_seed=initial_seed,
		dynamics_seed=dynamics_seed,
		snapshot_steps=snapshot_sweeps,
	)

	### Save only compact observables and optional requested snapshots
	with open(save_filename, 'wb') as out_file:
		energies, magnetization, neel, stripes, qea, local_field, snapshots = results
		pickle.dump((latt, energies, magnetization, neel, stripes, qea, local_field, snapshots), out_file)
